
###
POST http://localhost:9999/getCards?id=2 HTTP/1.1

// Данный запрос пришлёт данные карт пользователя, id которого вы укажете.

###
POST http://localhost:9999/getTransactions?id=2 HTTP/1.1

// Данный запрос пришлёт список с данными транзакций по карте, id которой вы укажете.







